create table shotoff(
card_type text,
coordinates text,
del text,
elapsed integer,
elapsed_plus integer,
event_incident_typefk  integer,
id integer,
match_id integer,
n integer,
player1 integer,
pos_x integer,
pos_y integer, 
shotoff text,
sortorder integer,
stats text,
subtype text,
team integer,
type text,
value text
)
