-- Table: public.team

-- DROP TABLE public.team;

CREATE TABLE public.team
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    team_api_id integer,
    team_fifa_api_id integer,
    team_long_name text COLLATE pg_catalog."default",
    team_short_name text COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.team
    OWNER to postgres;