-- Table: public.player_attributes

-- DROP TABLE public.player_attributes;

CREATE TABLE public.player_attributes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    player_fifa_api_id integer,
    player_api_id integer,
    date text COLLATE pg_catalog."default",
    overall_rating integer,
    potential integer,
    preferred_foot text COLLATE pg_catalog."default",
    attacking_work_rate text COLLATE pg_catalog."default",
    defensive_work_rate text COLLATE pg_catalog."default",
    crossing integer,
    finishing integer,
    heading_accuracy integer,
    short_passing integer,
    volleys integer,
    dribbling integer,
    curve integer,
    free_kick_accuracy integer,
    long_passing integer,
    ball_control integer,
    acceleration integer,
    sprint_speed integer,
    agility integer,
    reactions integer,
    balance integer,
    shot_power integer,
    jumping integer,
    stamina integer,
    strength integer,
    long_shots integer,
    aggression integer,
    interceptions integer,
    positioning integer,
    vision integer,
    penalties integer,
    marking integer,
    standing_tackle integer,
    sliding_tackle integer,
    gk_diving integer,
    gk_handling integer,
    gk_kicking integer,
    gk_positioning integer,
    gk_reflexes integer
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.player_attributes
    OWNER to postgres;